#!/bin/bash
#
# An example of shell variables.
#
echo Shell Variable Example
echo
echo The name of this shell is $0.
echo
echo A total of $# arguments were passed in to this shell.
echo
echo The first arguments are:
echo -e "\t$1"
echo -e "\t$2"
echo -e "\t$3"
echo
echo Here are all of the command line args:
echo $*
echo
echo The process ID for this shell is $$.
echo
MyLocalVar=5
echo MyLocalVar has a value of $MyLocalVar.
echo
echo Output from a command, like ls, can be stored in a variable like:
List=`ls`
echo
echo We can see what was placed in the variable by ls:
echo $List
echo
echo All Done.
echo





